name: CI Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Pull and run docker 🐋 
      shell: bash
      run: |
        docker run -it -d --name lake --mount type=bind,source="$(pwd)"/../lake,target=/lake keyiz/kratos-full bash
    - name: Install deps 🛠️
      shell: bash
      run: |
        docker exec -i lake bash -c 'apt update && apt install -y libgmp-dev libmpfr-dev libmpc-dev python3-dev'
        docker exec -i lake bash -c 'python3 -m pip install setuptools wheel'
        docker exec -i lake bash -c 'python3 -m pip install pytest fault pytest-codestyle pycodestyle'
        docker exec -i lake bash -c 'cd lake && python3 -m pip install -e .'
    - name: Run tests ⚙️
      shell: bash
      run: |
        docker exec -i lake bash -c 'lake/.github/scripts/run.sh'
