@name_outputs(
    data_out_1=BV[16],
    empty=Bit,
    stencil_valid=Bit,
    full=Bit,
    data_out_0=BV[16],
    sram_ready_out=Bit,
    valid_out_0=Bit,
    valid_out_1=Bit,
    config_data_out=BV[32],
)
def __call__(
    self,
    configs: Const(configs_adt),
    chain_data_in_0: BV[16],
    chain_data_in_1: BV[16],
    flush: Bit,
    config_read: Bit,
    ren_in_0: Bit,
    ren_in_1: Bit,
    config_en: BV[2],
    config_write: Bit,
    config_data_in: BV[32],
    clk_en: Bit,
    wen_in: BV[2],
    config_addr_in: BV[8],
    addr_in_0: BV[16],
    addr_in_1: BV[16],
    data_in_0: BV[16],
    data_in_1: BV[16],
) -> (BV[16], Bit, Bit, Bit, BV[16], Bit, Bit, Bit, BV[32]):

    circ_inputs = {}
    port = list(peak_configs)[0]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[1]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[2]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[3]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[4]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[5]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[6]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[7]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[8]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[9]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[10]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[11]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[12]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[13]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[14]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[15]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[16]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[17]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[18]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[19]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[20]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[21]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[22]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[23]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[24]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[25]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[26]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[27]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[28]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[29]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[30]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[31]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[32]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[33]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[34]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[35]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[36]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[37]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[38]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[39]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[40]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[41]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[42]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[43]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[44]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[45]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[46]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[47]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[48]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[49]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[50]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[51]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[52]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[53]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[54]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[55]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[56]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[57]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[58]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[59]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[60]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[61]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[62]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[63]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[64]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[65]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[66]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[67]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[68]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[69]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[70]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[71]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[72]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[73]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[74]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[75]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[76]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[77]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[78]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[79]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[80]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[81]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[82]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[83]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[84]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[85]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[86]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[87]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[88]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[89]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[90]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[91]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[92]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[93]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[94]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[95]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[96]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[97]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[98]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[99]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[100]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[101]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[102]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[103]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[104]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[105]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[106]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[107]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[108]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[109]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[110]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[111]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[112]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[113]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[114]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[115]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[116]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[117]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[118]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[119]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[120]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[121]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[122]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[123]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[124]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[125]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[126]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[127]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[128]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[129]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[130]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[131]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[132]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[133]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[134]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[135]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[136]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[137]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[138]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[139]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[140]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[141]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[142]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[143]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[144]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[145]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[146]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[147]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[148]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[149]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[150]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[151]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[152]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[153]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[154]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[155]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[156]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[157]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[158]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[159]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[160]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[161]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[162]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[163]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[164]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[165]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[166]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[167]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[168]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[169]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[170]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[171]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[172]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[173]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[174]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[175]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[176]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[177]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[178]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[179]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[180]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[181]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[182]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[183]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[184]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[185]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[186]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[187]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[188]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[189]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[190]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[191]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[192]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[193]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[194]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[195]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[196]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[197]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[198]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[199]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[200]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[201]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[202]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[203]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[204]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[205]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[206]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[207]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[208]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[209]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[210]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[211]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[212]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[213]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[214]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[215]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[216]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[217]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[218]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[219]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[220]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[221]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[222]
    circ_inputs[port] = getattr(configs, port)

    circ_inputs["addr_in_0"] = addr_in_0
    circ_inputs["addr_in_1"] = addr_in_1
    circ_inputs["config_write"] = config_write.ite(BV[1](1), BV[1](0))
    circ_inputs["config_en"] = config_en
    circ_inputs["config_data_in"] = config_data_in
    ren0 = ren_in_0.ite(BV[1](1), BV[1](0))
    ren1 = ren_in_1.ite(BV[1](1), BV[1](0))
    ren_in = BV[2].concat(ren0, ren1)
    circ_inputs["ren_in"] = ren_in
    circ_inputs["data_in_0"] = data_in_0
    circ_inputs["data_in_1"] = data_in_1
    circ_inputs["wen_in"] = wen_in
    circ_inputs["config_read"] = config_read.ite(BV[1](1), BV[1](0))
    circ_inputs["clk_en"] = clk_en.ite(BV[1](1), BV[1](0))
    circ_inputs["flush"] = flush.ite(BV[1](1), BV[1](0))
    circ_inputs["chain_data_in_0"] = chain_data_in_0
    circ_inputs["chain_data_in_1"] = chain_data_in_1
    circ_inputs["config_addr_in"] = config_addr_in

    circ_outputs = self.circ(**circ_inputs)

    outputs = {}
    port = output_attrs[0]
    circ_output = circ_outputs[0]
    outputs[port] = circ_output
    port = output_attrs[1]
    circ_output = circ_outputs[1]
    outputs[port] = circ_output
    port = output_attrs[2]
    circ_output = circ_outputs[2]
    outputs[port] = circ_output
    port = output_attrs[3]
    circ_output = circ_outputs[3]
    outputs[port] = circ_output
    port = output_attrs[4]
    circ_output = circ_outputs[4]
    outputs[port] = circ_output
    port = output_attrs[5]
    circ_output = circ_outputs[5]
    outputs[port] = circ_output
    port = output_attrs[6]
    circ_output = circ_outputs[6]
    outputs[port] = circ_output
    port = output_attrs[7]
    circ_output = circ_outputs[7]
    outputs[port] = circ_output
    port = output_attrs[8]
    circ_output = circ_outputs[8]
    outputs[port] = circ_output

    empty = outputs["empty"] == BV[1](1)
    stencil_valid = outputs["stencil_valid"] == BV[1](1)
    full = outputs["full"] == BV[1](1)
    sram_ready_out = outputs["sram_ready_out"] == BV[1](1)
    valid_out_0 = outputs["valid_out"][0]
    valid_out_1 = outputs["valid_out"][1]
    return (
        outputs["data_out_1"],
        empty,
        stencil_valid,
        full,
        outputs["data_out_0"],
        sram_ready_out,
        valid_out_0,
        valid_out_1,
        outputs["config_data_out_1"],
    )
