@name_outputs(
    output_width_16_num_0 = BV(16),
    output_width_16_num_1 = BV(16),
    output_width_1_num_1 = BV(1),
    output_width_1_num_2 = BV(1),
    output_width_1_num_3 = BV(1),
    config_data_out_0 = BV(32),
    config_data_out_1 = BV(32),
    output_width_1_num_0 = BV(1)
)
def __call__(
    self,
    configs: Const(configs_adt),
    clk_en: BV(1),
    config_write: BV(1),
    flush: BV(1),
    input_width_16_num_3: BV(16),
    input_width_16_num_0: BV(16),
    config_en: BV(2),
    config_read: BV(1),
    input_width_1_num_1: BV(1),
    input_width_16_num_2: BV(16),
    input_width_16_num_1: BV(16),
    config_addr_in: BV(8),
    config_data_in: BV(32),
    input_width_1_num_0: BV(1)
) -> (BV(16), BV(16), BV(1), BV(1), BV(1), BV(32), BV(32), BV(1)):

    circ_inputs = {}
    port = list(peak_configs)[0]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[1]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[2]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[3]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[4]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[5]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[6]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[7]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[8]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[9]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[10]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[11]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[12]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[13]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[14]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[15]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[16]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[17]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[18]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[19]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[20]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[21]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[22]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[23]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[24]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[25]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[26]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[27]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[28]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[29]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[30]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[31]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[32]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[33]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[34]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[35]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[36]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[37]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[38]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[39]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[40]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[41]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[42]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[43]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[44]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[45]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[46]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[47]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[48]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[49]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[50]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[51]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[52]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[53]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[54]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[55]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[56]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[57]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[58]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[59]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[60]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[61]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[62]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[63]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[64]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[65]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[66]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[67]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[68]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[69]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[70]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[71]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[72]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[73]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[74]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[75]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[76]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[77]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[78]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[79]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[80]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[81]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[82]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[83]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[84]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[85]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[86]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[87]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[88]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[89]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[90]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[91]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[92]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[93]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[94]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[95]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[96]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[97]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[98]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[99]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[100]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[101]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[102]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[103]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[104]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[105]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[106]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[107]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[108]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[109]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[110]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[111]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[112]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[113]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[114]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[115]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[116]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[117]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[118]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[119]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[120]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[121]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[122]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[123]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[124]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[125]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[126]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[127]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[128]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[129]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[130]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[131]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[132]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[133]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[134]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[135]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[136]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[137]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[138]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[139]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[140]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[141]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[142]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[143]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[144]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[145]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[146]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[147]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[148]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[149]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[150]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[151]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[152]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[153]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[154]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[155]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[156]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[157]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[158]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[159]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[160]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[161]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[162]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[163]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[164]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[165]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[166]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[167]
    circ_inputs[port] = getattr(configs, port)
    port = list(peak_configs)[168]
    circ_inputs[port] = getattr(configs, port)

    circ_inputs["clk_en"] = clk_en.ite(family.BitVector[1](1), family.BitVector[1](0))
    circ_inputs["config_write"] = config_write.ite(family.BitVector[1](1), family.BitVector[1](0))
    circ_inputs["flush"] = flush.ite(family.BitVector[1](1), family.BitVector[1](0))
    circ_inputs["config_en"] = config_en
    circ_inputs["config_read"] = config_read.ite(family.BitVector[1](1), family.BitVector[1](0))
    circ_inputs["config_addr_in"] = config_addr_in
    circ_inputs["config_data_in"] = config_data_in
    circ_inputs["input_width_16_num_3"] = input_width_16_num_3
    circ_inputs["input_width_16_num_0"] = input_width_16_num_0
    circ_inputs["input_width_1_num_1"] = input_width_1_num_1.ite(family.BitVector[1](1), family.BitVector[1](0))
    circ_inputs["input_width_16_num_2"] = input_width_16_num_2
    circ_inputs["input_width_16_num_1"] = input_width_16_num_1
    circ_inputs["input_width_1_num_0"] = input_width_1_num_0.ite(family.BitVector[1](1), family.BitVector[1](0))

    circ_outputs = self.circ(**circ_inputs)

    outputs = {}
    port = output_attrs[0]
    circ_output = circ_outputs[0]
    outputs[port] = circ_output
    port = output_attrs[1]
    circ_output = circ_outputs[1]
    outputs[port] = circ_output
    port = output_attrs[2]
    circ_output = circ_outputs[2]
    outputs[port] = circ_output
    port = output_attrs[3]
    circ_output = circ_outputs[3]
    outputs[port] = circ_output
    port = output_attrs[4]
    circ_output = circ_outputs[4]
    outputs[port] = circ_output
    port = output_attrs[5]
    circ_output = circ_outputs[5]
    outputs[port] = circ_output
    port = output_attrs[6]
    circ_output = circ_outputs[6]
    outputs[port] = circ_output
    port = output_attrs[7]
    circ_output = circ_outputs[7]
    outputs[port] = circ_output


    return (
        outputs["output_width_16_num_0"],
        outputs["output_width_16_num_1"],
        outputs["output_width_1_num_1"] == family.BitVector[1](1),
        outputs["output_width_1_num_2"] == family.BitVector[1](1),
        outputs["output_width_1_num_3"] == family.BitVector[1](1),
        outputs["config_data_out_0"],
        outputs["config_data_out_1"],
        outputs["output_width_1_num_0"] == family.BitVector[1](1)
    )
